#by jeff
LOCAL_DIR := $(call my-dir)
include $(CLEAR_VAR)

LOCAL_SRC_FILE:=src/amalloc.c
LOCAL_BIN_TARGET:=
LOCAL_MODULE:=malloc_test
LOCAL_TARGET_SUFFIX:=.a
LOCAL_INC_PATH:= 
LOCAL_EXPORT_INC_PATH:= $(LOCAL_DIR)
LOCAL_LINK_FLAGS:=
LOCAL_STATIC_LIBRARIES:= 
include $(BUILD_MODULE)


